src/lorepo/cron/urls.py
from django.urls import path
from src.lorepo.cron import views  # Import views module

urlpatterns = [
    path('keepalive', views.keepalive),
    path('delete_old_courses', views.delete_old_courses),
    path('delete_old_courses_cron', views.delete_old_courses_cron),
    path('delete_old_courses_async', views.delete_old_courses_async),
    path('lock_companies', views.lock_companies),
    path('lock_companies_cron', views.lock_companies_cron),
    path('lock_companies_async', views.lock_companies_async),
    path('is_more_users_in_company', views.is_more_users_in_company),
    path('is_more_users_in_company_cron', views.is_more_users_in_company_cron),
    path('is_more_users_in_company_async', views.is_more_users_in_company_async),
]

src/lorepo/home/urls.py
from django.urls import path
from src.lorepo.home import views

urlpatterns = [
    path('unpack_website/<int:website_id>/', views.unpack_website, name='unpack_website'),
]

src/rest_framework_custom/urls.py
from django.urls import re_path

from django.contrib.auth import views as auth_views

app_name = 'rest_framework_custom'  # ✅ this is the namespace
urlpatterns = [
    re_path(r'^login/$', auth_views.LoginView.as_view(template_name='rest_framework_custom/login.html'), name='login'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    re_path(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic import TemplateView
from src.lorepo.embed.views import present
from src.lorepo.user.views import register, custom_login
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='schema')),
    path('_ah/', include('djangae.urls')),
    path('api/docs/', include('rest_framework_docs.urls')),
    path('api/v2/', include(('src.lorepo.api.v2.urls', 'v2'), namespace='v2')),
    # path('api/v3/', include(('mcurriculum.api.v2.urls', 'v3'), namespace='v3')),  # For Future Use
    # cron => few of them are working, few needs authentication,
    path('cron/', include('src.lorepo.cron.urls')),
    # required database for website ids
    path('backendhome/', include('src.lorepo.home.urls')),
    # few urls are working and few needs payload
    path('file/', include('src.lorepo.filestorage.urls')),
    # few urls are working in user section
    path('user/', include('src.lorepo.user.urls')),

    path('assets/', include('src.lorepo.assets.urls')),

    path('labels/', include('src.lorepo.labels.urls')),

    path('doc/', include('src.libraries.wiki.urls')),

    path('spaces/', include('src.lorepo.spaces.urls')),

    path('translations/', include('src.lorepo.translations.urls')),
    re_path(r'^accounts/login/session/?$', custom_login, name='custom_login'),
    re_path(r'^api/v2/accounts/login/session/?$', custom_login, name='custom_login_v2'),
    path('accounts/', include('src.registration.urls')),
    path('accounts/', include(('rest_framework_custom.urls', 'rest_framework_custom'), namespace='rest_framework_custom')),
    path('corporate/', include('src.lorepo.corporate.urls')),
    path('exchange/', include('src.lorepo.exchange.urls')),
    path('merger/', include('src.lorepo.merger.urls')),
    path('newsletter/', include('src.lorepo.newsletter.urls')),
    path('proxy/', include('src.libraries.proxy.urls')),
    path('lessons_parsers/', include('src.mauthor.lessons_parsers.urls')),
    path('states/', include('src.mauthor.states.urls')),
    path('bug_track/', include('src.mauthor.bug_track.urls')),
    path('backup/', include('src.mauthor.backup.urls')),
    path('company/', include('src.mauthor.company.urls')),
    path('logger/', include('src.libraries.logger.urls')),
    path('localization/', include('src.mauthor.localization.urls')),
    path('exchange_narration/', include('src.mauthor.exchange_narration.urls')),
    path('indesign/', include('src.mauthor.indesign.urls')),
    path('pdfimport/', include('src.mauthor.pdfimport.urls')),
    path('metadata/', include('src.mauthor.metadata.urls')),
    path('search/', include('src.mauthor.search.urls')),
    path('customfixdb/', include('src.mauthor.customfixdb.urls')),
    path('gce/', include('src.mauthor.gce.urls')),

    # Regex-based URLs need re_path
    re_path(r'^mycontent/{0,1}', include('src.lorepo.mycontent.urls')),
    re_path(r'^public/{0,1}', include('src.lorepo.public.urls')),
    re_path(r'^support/{0,1}', include('src.lorepo.support.urls')),
    re_path(r'^editor/', include('src.lorepo.editor.urls')),
    re_path(r'^embed/', include('src.lorepo.embed.urls')),
    re_path(r'^present/(?P<content_id>\d+)$', present),
    re_path(r'^permission/{0,1}', include('src.lorepo.permission.urls')),
    re_path(r'^course/{0,1}', include('src.lorepo.course.urls')),
    re_path(r'^bulk/{0,1}', include('src.mauthor.bulk.urls')),

    # Static Template Views
    re_path(r'^pricing/{0,1}$', TemplateView.as_view(template_name='public/plans_and_pricing.html')),
    re_path(r'^about_us$', TemplateView.as_view(template_name='public/aboutus.html'))
]

# Serve static and media files in development
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/lorepo/course/models.py
from django.db import models
from src import settings
from src.lorepo.filestorage.models import FileStorage, UploadedFile
from src.lorepo.spaces.models import Space
from xml.dom import minidom
from src.lorepo.course.helpers import create_chapter_node, get_structure_chapters,\
    get_element_by_id, get_lessons_container, get_chapter_lessons,\
    get_or_create_node, get_or_create_child_node, get_child_nodes,\
    get_child_element_by
from src.lorepo.course.helpers import get_elements_by_id
import re
from django.template import loader
from django.template.context import Context
import logging
from src.lorepo.mycontent.models import Content
import src.libraries.utility.cacheproxy as cache


class Course(models.Model):
    name = models.CharField(max_length=200)
    structure_xml = models.ForeignKey(FileStorage, on_delete=models.DO_NOTHING)
    project = models.ForeignKey(Space, on_delete=models.DO_NOTHING)
    is_being_exported = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True, null=True)
    modified_date = models.DateTimeField(auto_now=True, null=True)

    def __unicode__(self):
        return str(self.name)

    def save(self, *args, **kwargs):
        if self.pk is not None:
            cache.set("course_%s" % self.pk, self, 60)
        super(Course, self).save(*args, **kwargs)

    @staticmethod
    def get_cached_course(course_id):
        course = cache.get("course_%s" % course_id)
        if not course:
            course = Course.objects.get(pk=course_id)
            cache.set("course_%s" % course_id, course, 60)
        return course

    def save_structure_xml(self, parsed_xml):
        course, created = get_or_create_node(parsed_xml, 'course')
        course.setAttribute('name', self.name)
        self.structure_xml.contents = re.sub(r'[\n\t\r]', '', parsed_xml.toxml(encoding='utf-8'))
        self.structure_xml.save()
        cache.delete("course_%s" % self.id)

    def _set_content_url(self, parsed_xml, content_type, exported_lesson):
        content_elements = get_elements_by_id(parsed_xml, content_type, exported_lesson.content.pk)

        for content_element in content_elements:
            content_element.setAttribute('url', '%s/file/serve/%s' % (settings.BASE_URL, exported_lesson.zipped_content.pk))
            gs_string = exported_lesson.zipped_content.path
            content_element.setAttribute('gs', gs_string)

    def save_exported_lessons(self, exported_lessons):
        try:
            parsed_xml = minidom.parseString(self.structure_xml.contents)

            for exported_lesson in exported_lessons:
                self._set_content_url(parsed_xml, 'ebook', exported_lesson)
                self._set_content_url(parsed_xml, 'lesson', exported_lesson)

            # Sanity check - in past there were situations, when for unknown reason there was missing 'url' attribute
            # for some elements. In that case - raise and exception and stop exporting course (it should not be
            # imported to mCourser).

            lesson_elements = parsed_xml.getElementsByTagName('lesson')
            for lesson_element in lesson_elements:
                if not lesson_element.hasAttribute('url'):
                    logging.error('Error while checking exported lesson XML representation (missing url attribute')
                    logging.error(lesson_element)
                    raise SyntaxError()

            ebook_elements = parsed_xml.getElementsByTagName('ebook')
            for ebook_element in ebook_elements:
                if not ebook_element.hasAttribute('url'):
                    logging.error('Error while checking exported eBook XML representation (missing url attribute')
                    logging.error(ebook_element)
                    raise SyntaxError()

            self.save_structure_xml(parsed_xml)
        except SyntaxError as e:
            raise e
        except Exception as e:
            import traceback
            logging.error('Error while saving exported lessons updated XML structure.')
            logging.error(traceback.format_exc())
            raise e

    def save_structure(self, chapters, lessons, eBooks):
        context = Context({'name': self.name, 'id': self.pk})
        parsed_xml = minidom.parseString(loader.get_template('initdata/course/root.xml').render(context).encode('utf-8'))
        for chapter in chapters:
            chapter_lessons = get_chapter_lessons(chapter, lessons)
            create_chapter_node(parsed_xml, chapter, chapter_lessons)
        self.save_structure_xml(parsed_xml)
        self.add_eBooks(eBooks)

    def set_id(self):
        parsed_xml = minidom.parseString(self.structure_xml.contents)
        course_element = parsed_xml.getElementsByTagName('course')[0]
        if not course_element.hasAttribute('id') or course_element.getAttribute('id') == '':
            course_element.setAttribute('id', str(self.pk))
        self.save_structure_xml(parsed_xml)

    def get_structure(self):
        parsed_xml = minidom.parseString(self.structure_xml.contents)

        return get_structure_chapters(parsed_xml)

    def remove_chapter(self, chapter_id):
        parsed_xml = minidom.parseString(self.structure_xml.contents)
        element = get_element_by_id(parsed_xml, 'chapter', chapter_id)
        if element:
            lessons = element.getElementsByTagName('lesson')
            lessons_ids = []
            for l in lessons:
                lessons_ids.append(l.getAttribute('lesson-id'))
            if len(lessons_ids):
                self._remove_elements(lessons_ids, 'resource')
                parsed_xml = minidom.parseString(self.structure_xml.contents)
                element = get_element_by_id(parsed_xml, 'chapter', chapter_id)
            parent = element.parentNode
            parent.removeChild(element)
            self.save_structure_xml(parsed_xml)

    def add_lessons_to_chapter(self, lessons, chapter_id):
        parsed_xml = minidom.parseString(self.structure_xml.contents)
        parent = get_element_by_id(parsed_xml, 'chapter', chapter_id)
        if parent:
            lessons_container = get_lessons_container(parsed_xml, parent)
            for lesson in lessons:
                lesson_element = parsed_xml.createElement('lesson')
                lesson_element.setAttribute('lesson-id', lesson['id'])
                lesson_element.setAttribute('name', lesson['name'])
                lesson_element.setAttribute('version', lesson['version'])
                lessons_container.appendChild(lesson_element)
            parent.appendChild(lessons_container)
            self.save_structure_xml(parsed_xml)
        else:
            return False

    def add_eBooks(self, eBooks):
        parsed_xml = minidom.parseString(self.structure_xml.contents)
        parent, _ = get_or_create_node(parsed_xml, 'ebooks')
        parsed_xml.documentElement.appendChild(parent)
        for eBook in eBooks:
            eBook_element = get_element_by_id(parsed_xml, 'ebook', eBook['id'])
            if not eBook_element:
                eBook_element = parsed_xml.createElement('ebook')
                eBook_element.setAttribute('ebook-id', eBook['id'])
                eBook_element.setAttribute('name', eBook['name'])
                if 'version' in eBook:
                    eBook_element.setAttribute('version', eBook['version'])
                else:
                    content = Content.get_cached_or_none(id = eBook['id'])
                    if content:
                        eBook_element.setAttribute('version', str(content.file.version))
                    else:
                        eBook_element.setAttribute('version', '0')
                if 'resources' in eBook and len(eBook['resources']) > 0:
                    logging.info(eBook['resources'])
                    eBook_element.appendChild(eBook['resources'][0])
                parent.appendChild(eBook_element)
        self.save_structure_xml(parsed_xml)

    def get_eBooks(self):
        parsed_xml = minidom.parseString(self.structure_xml.contents)
        eBooks_elements = parsed_xml.getElementsByTagName('ebook')
        eBooks = []
        for eBook_element in eBooks_elements:
            ebook_id = eBook_element.getAttribute('ebook-id')
            eBook = {
                'name': eBook_element.getAttribute('name'),
                'id': ebook_id,
                'is_deleted': Content.get_cached(id=ebook_id).is_deleted
            }
            eBooks.append(eBook)
        return eBooks

    def get_lessons_ids(self):
        return self._get_elements_ids('lesson')

    def get_eBooks_ids(self):
        return self._get_elements_ids('ebook')

    def update_ebooks(self, ids):
        self._update_elements(ids, 'ebook')

    def update_lessons(self, ids):
        self._update_elements(ids, 'lesson')

    def _update_elements(self, ids, element_type):
        parsed_xml = minidom.parseString(self.structure_xml.contents)
        for element_id in ids:
            elements = get_elements_by_id(parsed_xml, element_type, element_id)
            for element in elements:
                content = Content.get_cached(id = element_id)
                element.setAttribute('name', content.title)
                element.setAttribute('version', str(content.file.version))
        self.save_structure_xml(parsed_xml)

    def get_lessons_versions(self, ids):
        return self._get_element_versions('lesson', ids)

    def get_ebook_versions(self, ids):
        return self._get_element_versions('ebook', ids)

    def _get_element_versions(self, element_type, ids):
        parsed_xml = minidom.parseString(self.structure_xml.contents)
        versions_dict = {}
        for element_id in ids:

src/lorepo/editor/models.py
from django.contrib.auth.models import User
from django.db import models


class UserFeedback(models.Model):
    created_date = models.DateTimeField()
    content = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    
    def __str__(self):
        return self.content

src/lorepo/global_settings/models.py
from gcloudc.db.models.fields.json import JSONField

import src.libraries.utility.cacheproxy as cache
from src.lorepo.util.singleton_model import SingletonModel


class GlobalSettings(SingletonModel):
    referrers = JSONField()

    CACHE_KEY = 'global_settings'
    CACHE_TIME = 24 * 60 * 60 * 7

    def save(self, *args, **kwargs):
        super(GlobalSettings, self).save(*args, **kwargs)
        self.set_cache()

    def set_cache(self):
        cache.set(self.CACHE_KEY, self, timeout=self.CACHE_TIME)

    @classmethod
    def get_cached(cls):
        global_settings = cache.get(cls.CACHE_KEY)
        if not global_settings:
            global_settings = cls.load()
            global_settings.set_cache()
        return global_settings

src/lorepo/labels/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.db import models


class Label(models.Model):
    """
    Etykieta którą można przypisać do contentu. Służy do grupowania
    """
    title = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    
    class Meta:
        ordering = ('title',)

    def __str__(self):
        return self.title

src/lorepo/token/models.py
class TOKEN_KEYS(object):
    PUBLICATION_ACTION = "publication_action"
    PROJECT_STATES = "project_states"
    MYCONTENT_EDITOR = "mycontent_editor"
    MYCONTENT_EDIT_ADDON = 'mycontent_edit_addon'
    KANBAN = 'kanban'

src/lorepo/templates/mycontent/add_addon.html
{% extends "base.html" %}
{% load i18n %}
{% load apptags %}
{% block content %}
<div class="createDiv">
<h2>Create Addon</h2>

<form method="post" action="/mycontent/addon{% if space_id %}/{{space_id}}{% endif %}" name="create">
	{% csrf_token %}
	<input type="hidden" value="{{next}}" name="next" />
	<div class="title-tags">
		<label for="id_title">{% trans "Title" %}:
			<div class="errorlist">{% for e in form.title.errors %}{{ e }}{% endfor %}</div>
		</label>
		<div>
			<input id="id_title" type="text" size="60" name="title" value="{{form.data.title}}" autofocus="autofocus" />
		</div>
		<label for="id_name">{% trans "Name" %}: 
			<div class="errorlist">{% for e in form.name.errors %}{{ e }}{% endfor %}</div>
		</label>
		<div>
			<input id="id_name" type="text" size="60" name="name" value="{{form.data.name}}"/>
		</div>
		<label for="id_tags">{% trans "Tags" %} <span style="font-size:0.8em">(Must be comma separated)</span>:
			<div class="errorlist">{% for e in form.tags.errors %}{{ e }}{% endfor %}</div>
		</label>
		<div>
			<textarea rows="4" id="id_tags" name="tags">{{form.data.tags}}</textarea>
		</div>
	</div>
	<div class="description-shortdescription">
		<label for="id_short">{% trans "Short Description" %}:
			<div class="errorlist">{% for e in form.short_description.errors %}{{ e }}{% endfor %}</div>
		</label>
		<div>
			<textarea id="id_short" style="width:100%;" rows="4" name="short_description">{{form.data.short_description}}</textarea>
		</div>
		<label for="id_desc">{% trans "Description" %}:
			<div class="errorlist">{% for e in form.description.errors %}{{ e }}{% endfor %}</div>
		</label>
		<div>
			<textarea id="id_desc" style="width:100%;" rows="10" name="description">{{form.data.description}}</textarea>
		</div>
	</div>
	<div style="float:left">{% button 'Create' 'jQuery(this).hide();document.forms["create"].submit();' %}</div>
	{% with next as next %}
		{% with "location.href='"|add:next|add:"'" as url %}
			<div style="float:right">{% button 'Cancel' url %}</div>
		{% endwith %}
	{% endwith %}
</form>
<div class="content clear"></div>
</div>

{% endblock %}

src/lorepo/templates/mycontent/addon_metadata.html
{% extends "base.html" %}
{% load i18n %}
{% load apptags %}
{% block content %}
<div class="createDiv">
<h2>Edit Addon</h2>

<form method="post" action="/mycontent/{{addon.id}}/addonmetadata" name='metadata'>
	{% csrf_token %}
	<input type="hidden" name="next" value="{{ next }}" />
	<div class="title-tags">
		<label for="id_title">{% trans "Title" %}: {% for e in form.title.errors %}
			<span class="errorlist">&lArr; {{ e }}</span>{% endfor %}
		</label>
		<br/>
		<input id="id_title" type="text" size="60" name="title" value="{{form.data.title}}"/>
		<br />
		<label for="id_tags">{% trans "Tags" %}
			<span style="font-size:0.8em">(Must be comma separated)</span>:
		</label>
		<br/>
		<textarea rows="4" id="id_tags" name="tags">{{form.data.tags}}</textarea>
	</div>
	<div class="description-shortdescription">
		<label for="id_short">{% trans "Short Description" %}:{% for e in form.short_description.errors %}
			<span class="errorlist">&lArr; {{ e }}</span>{% endfor %}
		</label>
		<br/>
		
		<textarea id="id_short" rows="4" name="short_description">{{form.data.short_description}}</textarea>
		<label for="id_desc">{% trans "Description" %}:</label>
		<br/>
		<textarea id="id_desc" rows="10" name="description">{{form.data.description}}</textarea>
	</div>
	<div style="float:left;">
			{% button 'Send' 'document.forms["metadata"].submit()' %}
		</div>
		{% with next as next %}
			{% with "location.href='"|add:next|add:"'" as url %}
				<div style="float:right">{% button 'Cancel' url %}</div>
			{% endwith %}
		{% endwith %}
</form>
		<div class="content clear"></div>
</div>

{% endblock %}

src/lorepo/templates/mycontent/changeicon.html
{% extends "base.html" %}
{% load i18n %}
{% load apptags %}
{% block head %}
	<script src="/media/agileuploader/jquery.flash.min.js" type="text/javascript"></script>
	<script src="/media/agileuploader/agile-uploader-3.0.js" type="text/javascript"></script>
	
{% endblock %}


{% block content %}

<h1 class="page_header">{% trans "Change icon" %}</h1>
<div class="main clear" style="padding-top: 0"></div>

<div style="float:left; padding:10px;">
{% if content.content_type == 3 %}
	{% if content.icon_href != None %}
		<img src="{{content.icon_href}}" style="border:0px none;" />
	{% else %}
		<img src="/media/content/default_small_addon.png" style="border:0px none;" />
	{% endif %}
{% else %}
	{% if content.icon_href != None %}
		<img src="{{content.icon_href}}" style="border:1px solid lightgray;"/>
	{% else %}
		<img src="/media/content/default_presentation.png" style="border:1px solid lightgray;"/>
	{% endif %}
{% endif %}
</div>
<form name="upload" method="post" enctype="multipart/form-data" action="{{upload_url}}">
	<table class="upload-logo">
			{{ form }}
		<tr><th></th><th><button role="submit" class="btn btn-primary btn-sm">Upload</button></th></tr>
	</table>
	<input type="hidden" value="{{next}}" name="next" />
	<input type="submit" value="upload" />
</form>

{% endblock %}

src/lorepo/templates/mycontent/children.html
{% for space in spaces %}
	<option value="{{space.id}}" {% if space.id == selected_space.id %}selected{% endif %}>{{param}} {{space.title}}</option>
	{% with param|add:space.title|add:" -> " as inner_param %}
		{% children_tag_select space.kids.all inner_param selected_space %}
	{% endwith %}
{% endfor %}


src/lorepo/templates/mycontent/confirm_edit_content.html
{% extends "base.html" %}
{% load apptags %}
{% load utility %}

{% block content %}
<div class="alert alert-info alert-narrow alert-block">
	This lesson is currently being edited by {{who_editing}}. If you modify it, {{username}} might lose all changes.
	Are you sure you want to continue?
</div>
<a role="button" class="btn btn-primary btn-sm pull-left" href="{{full_path_to_editor}}&confirmed=True">Yes</a>
<a role="button" class="btn btn-primary btn-sm pull-right" href="{{back}}">No</a>
<div class="clearfix"></div> 
{% endblock %}

src/lorepo/templates/mycontent/metadata.html
{% extends "base.html" %}
{% load i18n %}
{% load apptags %}
{% load spaces %}
{% load metadata %}

{%  block head %}
    <script type="text/javascript">
		$(document).ready(function() {
    			$('.remove').click(function() {
				$(this).parent().parent().addClass('removed'); // we move up to the div class="metadata-element"
                $(this).parent().addClass('hidden');
                $(this).parent().parent().find('.add-wrapper').removeClass('hidden');
                $(this).parent().parent().find('#unused').attr('value','true');
                $(this).parent().parent().find('.entered-value').attr('disabled','true');
			});

            $('.add').click(function() {
				$(this).parent().parent().removeClass('removed'); // we move up to the div class="metadata-element"
                $(this).parent().addClass('hidden');
                $(this).parent().parent().find('.remove-wrapper').removeClass('hidden');
                $(this).parent().parent().find('#unused').attr('value','false');
                $(this).parent().parent().find('.entered-value').removeAttr('disabled');
			});
		});
	</script>
{%  endblock head %}

{% block content %}

<div class="createDiv">
<h2>Edit lesson metadata</h2>

<form method="post" action="/mycontent/{{content.id}}/metadata" name="metadata">
	{% csrf_token %}
	<input type="hidden" name="next" value="{{ next }}" />
		<div class="title-tags">
			<label for="id_title">{% trans "Title" %}: {% for e in form.title.errors %}
				<span class="errorlist">&lArr; {{ e }}</span>{% endfor %}
			</label>
			<br/>
			<input id="id_title" type="text" size="60" name="title" value="{{form.data.title}}" {% if language_bidi %}dir="rtl"{% endif %}/>
			<br />
			<label>{% trans "Tags" %} 
				<span style="font-size:0.8em">(Must be comma separated)</span>:
			</label>
			<br/>
			<textarea rows="4" id="id_tags" name="tags" {% if language_bidi %}dir="rtl"{% endif %}>{{form.data.tags}}</textarea>
		</div>
		<div class="description-shortdescription">
			<label for="id_short">{% trans "Short Description" %}:{% for e in form.short_description.errors %}
				<span class="errorlist">&lArr; {{ e }}</span>{% endfor %}</label>
			<br/>
			
			<textarea id="id_short" cols="63" rows="4" name="short_description" {% if language_bidi %}dir="rtl"{% endif %}>{{form.data.short_description}}</textarea>
			<label >{% trans "Description" %}:</label>
			<br/>
			<textarea cols="63" rows="10" name="description" {% if language_bidi %}dir="rtl"{% endif %}>{{form.data.description}}</textarea>
			<div>
				<label>Score type:
					{% for e in form.passing_score.errors %}
						<span class="errorlist">&lArr; {{ e }}</span>
					{% endfor %}
				</label><br/>
				<select id="id_score_type" name="score_type">
					<option value="last" {% if content.get_score_type == 'last'%}selected{% endif %}>last</option>
					<option value="first" {% if content.get_score_type == 'first'%}selected{% endif %}>first</option>
				</select>
			</div>
			<div>
				<label>Passing score: <span style="font-size:0.8em">(0-100 without percent sign)</span>
					{% for e in form.passing_score.errors %}
						<span class="errorlist">&lArr; {{ e }}</span>
					{% endfor %}
				</label><br/>
				<input id="id_passing_score" type="text" name="passing_score" value="{{form.data.passing_score}}"/> %
			</div>
		</div>
		<div class="category-is_template">
			<div>
				<label>{% trans "Category" %}:</label>
				<br/>
				<select name="space_id">
					{% for space in spaces %}
						{% if space.parent == None %}
							<option value="{{space.id}}" {% if space.id == priv_space.id %}selected{% endif %}>--</option>
						{% endif %}
					{% endfor %}				
					{% for space in spaces %}
						{% if space.parent != None %}
							<option value="{{space.id}}" {% if space.id == priv_space.id %}selected{% endif %}>{{space.title}}</option>
						{% endif %}
					{% endfor %}
				</select>
			</div>
		</div>
		<div class="category-is_template">
			<div>
				<input type="checkbox" name="is_template" {% if is_template %}checked{% endif %}/><label>Is Template</label><br/>
			</div>
		</div>
		<div class="category-is_template">
			<div>
				<input id="id_enable_page_metadata" type="checkbox" name="enable_page_metadata" {% if content.enable_page_metadata %}checked{% endif %}/><label>Enable page metadata</label><br/>
			</div>
			{% if definitions %}
			<div>
				<h3>Custom metadata</h3>
				{% for definition in definitions %}
					{% render_definition_form definition language_bidi %}
				{% endfor %}
			</div>
			{% endif %}
		</div>
		

		<a role="button" class="btn btn-primary btn-sm pull-left" href="javascript:$('.entered-value').removeAttr('disabled');jQuery(this).hide();document.forms['metadata'].submit();">Send</a>
		<a role="button" class="btn btn-primary btn-sm pull-right" href="/mycontent/{{content.id}}/cancelediting?next={{next}}">Cancel</a>
</form>
		<div class="clearfix"></div>
</div>

{% endblock %}