src/lorepo/cron/urls.py
from django.urls import path
from src.lorepo.cron import views  # Import views module

urlpatterns = [
    path('keepalive', views.keepalive),
    path('delete_old_courses', views.delete_old_courses),
    path('delete_old_courses_cron', views.delete_old_courses_cron),
    path('delete_old_courses_async', views.delete_old_courses_async),
    path('lock_companies', views.lock_companies),
    path('lock_companies_cron', views.lock_companies_cron),
    path('lock_companies_async', views.lock_companies_async),
    path('is_more_users_in_company', views.is_more_users_in_company),
    path('is_more_users_in_company_cron', views.is_more_users_in_company_cron),
    path('is_more_users_in_company_async', views.is_more_users_in_company_async),
]

src/lorepo/home/urls.py
from django.urls import path
from src.lorepo.home import views

urlpatterns = [
    path('unpack_website/<int:website_id>/', views.unpack_website, name='unpack_website'),
]

src/rest_framework_custom/urls.py
from django.urls import re_path

from django.contrib.auth import views as auth_views

app_name = 'rest_framework_custom'  # ✅ this is the namespace
urlpatterns = [
    re_path(r'^login/$', auth_views.LoginView.as_view(template_name='rest_framework_custom/login.html'), name='login'),
    re_path(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    re_path(r'^password_reset/$', auth_views.PasswordResetView.as_view(), name='password_reset'),
]

src/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.generic import TemplateView
from src.lorepo.embed.views import present
from src.lorepo.user.views import register, custom_login
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/schema/', SpectacularAPIView.as_view(), name='schema'),
    path('api/docs/', SpectacularSwaggerView.as_view(url_name='schema')),
    path('_ah/', include('djangae.urls')),
    path('api/docs/', include('rest_framework_docs.urls')),
    path('api/v2/', include(('src.lorepo.api.v2.urls', 'v2'), namespace='v2')),
    # path('api/v3/', include(('mcurriculum.api.v2.urls', 'v3'), namespace='v3')),  # For Future Use
    # cron => few of them are working, few needs authentication,
    path('cron/', include('src.lorepo.cron.urls')),
    # required database for website ids
    path('backendhome/', include('src.lorepo.home.urls')),
    # few urls are working and few needs payload
    path('file/', include('src.lorepo.filestorage.urls')),
    # few urls are working in user section
    path('user/', include('src.lorepo.user.urls')),

    path('assets/', include('src.lorepo.assets.urls')),

    path('labels/', include('src.lorepo.labels.urls')),

    path('doc/', include('src.libraries.wiki.urls')),

    path('spaces/', include('src.lorepo.spaces.urls')),

    path('translations/', include('src.lorepo.translations.urls')),
    re_path(r'^accounts/login/session/?$', custom_login, name='custom_login'),
    re_path(r'^api/v2/accounts/login/session/?$', custom_login, name='custom_login_v2'),
    path('accounts/', include('src.registration.urls')),
    path('accounts/', include(('rest_framework_custom.urls', 'rest_framework_custom'), namespace='rest_framework_custom')),
    path('corporate/', include('src.lorepo.corporate.urls')),
    path('exchange/', include('src.lorepo.exchange.urls')),
    path('merger/', include('src.lorepo.merger.urls')),
    path('newsletter/', include('src.lorepo.newsletter.urls')),
    path('proxy/', include('src.libraries.proxy.urls')),
    path('lessons_parsers/', include('src.mauthor.lessons_parsers.urls')),
    path('states/', include('src.mauthor.states.urls')),
    path('bug_track/', include('src.mauthor.bug_track.urls')),
    path('backup/', include('src.mauthor.backup.urls')),
    path('company/', include('src.mauthor.company.urls')),
    path('logger/', include('src.libraries.logger.urls')),
    path('localization/', include('src.mauthor.localization.urls')),
    path('exchange_narration/', include('src.mauthor.exchange_narration.urls')),
    path('indesign/', include('src.mauthor.indesign.urls')),
    path('pdfimport/', include('src.mauthor.pdfimport.urls')),
    path('metadata/', include('src.mauthor.metadata.urls')),
    path('search/', include('src.mauthor.search.urls')),
    path('customfixdb/', include('src.mauthor.customfixdb.urls')),
    path('gce/', include('src.mauthor.gce.urls')),

    # Regex-based URLs need re_path
    re_path(r'^mycontent/{0,1}', include('src.lorepo.mycontent.urls')),
    re_path(r'^public/{0,1}', include('src.lorepo.public.urls')),
    re_path(r'^support/{0,1}', include('src.lorepo.support.urls')),
    re_path(r'^editor/', include('src.lorepo.editor.urls')),
    re_path(r'^embed/', include('src.lorepo.embed.urls')),
    re_path(r'^present/(?P<content_id>\d+)$', present),
    re_path(r'^permission/{0,1}', include('src.lorepo.permission.urls')),
    re_path(r'^course/{0,1}', include('src.lorepo.course.urls')),
    re_path(r'^bulk/{0,1}', include('src.mauthor.bulk.urls')),

    # Static Template Views
    re_path(r'^pricing/{0,1}$', TemplateView.as_view(template_name='public/plans_and_pricing.html')),
    re_path(r'^about_us$', TemplateView.as_view(template_name='public/aboutus.html'))
]

# Serve static and media files in development
if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/libraries/wiki/models.py
from django.contrib.auth.models import User
from django.db import models
from django.template.loader import render_to_string
from src.lorepo.filestorage.models import UploadedFile
import src.libraries.utility.cacheproxy as cache
from src.lorepo.mycontent.models import Content
from src.lorepo.util.searchable_models import Indexable
from src.markdown import markdown
from src.settings import USER_LANGUAGES, LANGUAGES

class WikiPage(models.Model):
    title = models.CharField(max_length=200)
    text = models.TextField()
    modified_date = models.DateTimeField(null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    is_toc = models.BooleanField(default=False)
    url = models.CharField(max_length=200)
    parent = models.ForeignKey('self', null=True, blank=True, related_name="kids", on_delete=models.DO_NOTHING)
    order = models.IntegerField(null=True)

    def __str__(self):
        return self.title


class PrivateAddonWikiPageManager(models.Manager):
    def get_or_create(self, defaults=None, **kwargs):
        try:
            return super(PrivateAddonWikiPageManager, self).get_or_create(defaults=defaults, **kwargs)
        except self.model.MultipleObjectsReturned:
            """
                WikiPage will be created on demand, so there can be more than one page in the database for the same 
                addon by eventual consistency.
                In this case, we want to return only the first page from the database.
            """
            lookup, _ = self._extract_model_params(defaults, **kwargs)
            return self.filter(**lookup).first(), False


class PrivateAddonWikiPage(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    text = models.TextField()
    addon = models.ForeignKey(Content, on_delete=models.DO_NOTHING)

    objects = PrivateAddonWikiPageManager()

    @staticmethod
    def get_default_text():
        return render_to_string('initdata/addon/addon.md').encode('utf-8')

    def get_page(self):
        return markdown(self.text)


class WikiPageTranslated(models.Model):
    created_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(null=True)     #don't use the auto_now feature
    title = models.CharField(max_length=200)
    text = models.TextField()
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    is_toc = models.BooleanField(default=False)
    url = models.CharField(max_length=200)
    parent = models.ForeignKey('self', null=True, blank=True, related_name="kids", on_delete=models.DO_NOTHING)
    order = models.IntegerField(null=True)
    language_code = models.CharField(max_length=10, null=True)

    def __str__(self):
        return self.title


    def load_kids(self):
        self.loaded_kids = self.kids.filter(language_code='en').order_by('order')
        for p in self.loaded_kids:
            p.load_kids()


    @staticmethod
    def load_toc_kids(page_dict):
        page_dict['loaded_kids'] = []
        page_dict['loaded_kids'] = WikiPageTranslated.objects.filter(parent=page_dict['id'], language_code=page_dict['language_code'])
        page_dict['loaded_kids'] = page_dict['loaded_kids'].order_by('order').values('id', 'title', 'url', 'parent', 'order', 'is_toc', 'language_code')
        for pd in page_dict['loaded_kids']:
            WikiPageTranslated.load_toc_kids(pd)

    @staticmethod
    def translate_kids(toc, translated_toc, lang_code):
        for pd in toc:
            page = WikiPageTranslated.objects.filter(url=pd['url'], language_code=lang_code)
            page = page.values('id', 'title', 'url', 'parent', 'order', 'is_toc', 'language_code')[0]
            page['loaded_kids'] = []
            WikiPageTranslated.translate_kids(pd['loaded_kids'], page['loaded_kids'],  lang_code)
            translated_toc.append(page)

    @staticmethod
    def toc_pages(lang_code):
        if lang_code == 'en':
            toc_en = cache.get('wiki_pages_toc_en')
            if not toc_en:
                toc_en = WikiPageTranslated.objects.filter(parent=None, is_toc=True, language_code='en')
                toc_en = toc_en.order_by('order').values('id', 'title', 'url', 'parent', 'order', 'is_toc', 'language_code')
                for page_dict in toc_en:
                    WikiPageTranslated.load_toc_kids(page_dict)
                cache.set('wiki_pages_toc_en', toc_en)
            return toc_en
        else:
            toc = cache.get('wiki_pages_toc_%s' % (lang_code))
            if not toc:
                toc_en = WikiPageTranslated.toc_pages('en')
                toc = []
                WikiPageTranslated.translate_kids(toc_en, toc, lang_code)
                cache.set('wiki_pages_toc_%s' % (lang_code), toc)
            return toc


    @staticmethod
    def flush_toc():
        for lang in LANGUAGES:
             cache.delete('wiki_pages_toc_%s' % (lang[0]))

    @staticmethod
    def _pages_for_url(url):
        page_translations = cache.get("wiki_page_translated_%s"%(url))
        if not page_translations:
            page_translations = list(WikiPageTranslated.objects.filter(url=url))
            if page_translations:
                cache.set("wiki_page_translated_%s"%(url), page_translations)
        return page_translations

    @staticmethod
    def page_for_url(url, lang_code):
        page_translations = WikiPageTranslated._pages_for_url(url)
        for page in page_translations:
            if page.language_code == lang_code:
                return page
        return None

    @staticmethod
    def validated_language_code(lang_code=None, languages = USER_LANGUAGES):
        if not lang_code:
            return 'en'
        lang_codes = [lang[0] for lang in languages]
        return lang_code if lang_code in lang_codes else 'en'


    def clone_for_languages(self, lang_list=LANGUAGES):
        for language in lang_list: #omit 'en' which is always first
            if language[0] == self.language_code:
                continue #make sure we don't make copy of the default
            try:
                page_copy = WikiPageTranslated.objects.get(url = self.url, language_code = language[0])
            except WikiPageTranslated.DoesNotExist:
                page_copy = WikiPageTranslated(
                    url = self.url,
                    language_code = language[0],
                    title = self.title,
                    text = self.text,
                    modified_date=self.modified_date,
                    is_toc=self.is_toc
                )
                page_copy.author_id = self.author_id
                page_copy.save()

    def get_translations(self):
        try:
            return self._translations
        except AttributeError:
            page_translations = WikiPageTranslated._pages_for_url(self.url)
            self._translations = {}
            for page in page_translations:
                if page.id != self.id:
                    page.needs_update = True if page.modified_date <= self.modified_date else False
                    self._translations[page.language_code] = page
            self._translations[self.language_code] = self
        return self._translations


    def save(self, *args, **kwargs):
        if self.url:
            cache.delete("wiki_page_translated_%s"%(self.url))

        WikiPageTranslatedIndex(wiki_page_translated_entity=self).save()
        return super(WikiPageTranslated, self).save(*args, **kwargs)

    def delete(self, using=None):
        if self.url:
            cache.delete("wiki_page_translated_%s"%(self.url))
        WikiPageTranslatedIndex(wiki_page_translated_entity=self).delete()
        super(WikiPageTranslated, self).delete(using)


class WikiFile(models.Model):
    uploaded_file = models.ForeignKey(UploadedFile, null=True, on_delete=models.DO_NOTHING)


class WikiPageTranslatedIndex(Indexable):
    wiki_page_translated_entity = models.ForeignKey(WikiPageTranslated, null=True, blank=True, on_delete=models.CASCADE)

    _search_indexed_fields = ['title',
                              'text',
                              'is_toc',
                              'url',
                              'parent',
                              'order',
                              'language_code'
                              ]

    _search_indexed_tokenized_fields = ['title']

    _sorted_fields = ['title']

    def get_doc_id(self):
        if self.doc_id is None:
            self.doc_id = str(self.wiki_page_translated_entity.pk)
        return self.doc_id

    @property
    def title(self):
        return self.wiki_page_translated_entity.title

    @property
    def text(self):
        return self.wiki_page_translated_entity.text

    @property
    def is_toc(self):
        return self.wiki_page_translated_entity.is_toc

    @property
    def url(self):
        return self.wiki_page_translated_entity.url

    @property
    def parent(self):
        return self.wiki_page_translated_entity.parent

    @property
    def order(self):
        return self.wiki_page_translated_entity.order

    @property
    def language_code(self):
        return self.wiki_page_translated_entity.language_code

src/lorepo/editor/models.py
from django.contrib.auth.models import User
from django.db import models


class UserFeedback(models.Model):
    created_date = models.DateTimeField()
    content = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    
    def __str__(self):
        return self.content

src/lorepo/labels/models.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.db import models


class Label(models.Model):
    """
    Etykieta którą można przypisać do contentu. Służy do grupowania
    """
    title = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.DO_NOTHING)
    
    class Meta:
        ordering = ('title',)

    def __str__(self):
        return self.title

src/libraries/wiki/forms.py
from django import forms
from src.libraries.wiki.models import WikiPage, WikiPageTranslated
from django.core.exceptions import ValidationError
from src.libraries.wiki.util import make_url


class WikiPageForm(forms.Form):
    title = forms.CharField(error_messages={'required': 'Title is a required field'})
    text = forms.CharField(error_messages={'required': 'Text is a required field'})

    def clean_title(self):
        title = self.cleaned_data['title']
        url = make_url(title)
        pk = self.data['id']
        if pk == '':
            pk = 0
        else:
            pk = int(self.data['id'])

        if len(WikiPage.objects.filter(url=url)) > 0:
            for wp in WikiPage.objects.filter(url=url):
                if wp.id != pk:
                    raise ValidationError('Object with title ' + title + ' already exist')

        return self.cleaned_data['title']


class WikiPageTranslatedForm(forms.Form):
    title = forms.CharField(error_messages={'required': 'Title is a required field'})
    text = forms.CharField(error_messages={'required': 'Text is a required field'})

    def clean_title(self):
        title = self.cleaned_data['title']
        url = make_url(title)
        pk = self.data['id']
        if pk == '':
            pk = 0
        else:
            pk = int(self.data['id'])

        if len(WikiPageTranslated.objects.filter(url=url)) > 0:
            for wp in WikiPageTranslated.objects.filter(url=url):
                if wp.id == pk:
                    return self.cleaned_data['title']

        raise ValidationError('Object with title ' + title + ' already exist')



src/lorepo/templates/wiki/add_file.html
{% extends "base.html" %}
{% load apptags %}
{% load markdown_deux_tags %}

{% block content %}
<h1 class="page_header">Add File</h1>
<div class="main clear" style="padding-top: 0"></div>

<div>
{% button 'Go Back' 'history.go(-1)' %}
<p>If you want to put one of those files into your Wiki Page:</p>
<p>1) Copy text from input below the file/image.</p>
<p>2) Go back.</p>
<p>3) Paste anywhere you want.</p>
<p>4) <a href="/doc/upload?next={{request.path}}">Or upload a new file</a></p>
<ul style="list-style:none;">
{% for file in files %}
	<li style="margin:20px 0">
	{% if 'image' in file.content_type %}
		<div>
			<img src="/file/serve/{{file.id}}" width="128" height="96" />
		</div>
		<div>
			<input type="text" value="<img src='/file/serve/{{file.id}}' />" size="40" />
		</div>
	{% else %}
		<div>
			This file is not an image.
		</div>
		<div>
			<input type="text" value="<a href='/file/serve/{{file.id}}'>Download</a>" size="40" />
		</div>
		
	{% endif %}
	</li>
{% endfor %}
</ul>

</div>
{% endblock %}

src/lorepo/templates/wiki/addpage.html
{% extends "base.html" %}
{% load i18n %}
{% load apptags %}

{% block head %}
 <script type="text/javascript" src="/media/js/wiki.js"></script>
{% endblock %}

{% block content %}
<h1 class="page_header">Add Page</h1>
<div class="main clear" style="padding-top: 0"></div>

<form action="add" method="post" name="add">
	<div class="button-left">{% button 'Add File' 'parent.location="/doc/file"' '' '1,4em;' %}</div>
	<div class="clear"></div>
	{% csrf_token %}
	<table>
	<tr>
			<td></td>
			<td><input id="id_id" type="hidden" name="id" value=""/></td>
		</tr>
	<tr>
		<td></td>
		<td>
		{% if 'title' in request.GET %}
			This page doesn't exist yet. You can create it here.
		{% endif %}
			{{ form.title.errors }}
			{{ form.text.errors }}
		</td>
	</tr>
		<tr>
			<td><label for="id_title">{% trans "Title" %}:</label></td>
			<td><input id="id_title" type="text" name="title" value="{% if title %}{{ title }}{% endif %}{% if not title and form.title.value %}{{form.title.value}}{% endif %}" size="80"/></td>
		</tr>
		<tr>
			<td style="vertical-align:top"><label for="id_text">{% trans "Text" %}:</label></td>
			<td><textarea id="id_text" name="text" rows="20" cols="80">{{form.text.value}}</textarea></td>
		</tr>
		<tr>
			<td  colspan="2">
				<input type="submit" value="{% trans "Send" %}" />
				<div class="button-left">
					{% button 'Send' 'document.forms["add"].action="/doc/add";document.forms["add"].submit();localStorage.clear()' %}
				</div>
				<div class="button-left">
					{% button 'Preview' 'document.forms["add"].action="/doc/preview";document.forms["add"].submit(); setWikiPage()' %}
				</div>
				<div class="button-left">
					{% button 'Cancel' 'parent.location="/doc"; localStorage.clear()' %}
				</div>
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<a href="http://en.wikipedia.org/wiki/Markdown" target="_blank" class="normal">Markdown syntax</a>
			</td>
		</tr>
	</table>
</form>

<script>
$(document).ready(function() { getWikiPage(); });
</script>

{% endblock %}

src/lorepo/templates/wiki/edit.html
{% extends "base.html" %}
{% load i18n %}
{% load apptags %}


{% block head %}
 <script type="text/javascript" src="/media/js/wiki.js"></script>
{% endblock %}

{% block title %}
	Edit {{ page.title }}
{% endblock %}

{% block content %}

<h1 class="page_header">Edit Page</h1>
<div class="main clear" style="padding-top: 0"></div>


<form action="{{page.id}}" method="post" name="edit">
	<div class="button-left">{% button 'Add File' 'parent.location="/doc/file"' '' '1,4em;' %}</div>
	<div class="clear"></div>
	{% csrf_token %}
	<table>
		<tr>
			<td></td>
			<td><input id="id_id" type="hidden" name="id" value="{{page.id}}"/></td>
		</tr>
		<tr>
			<td></td>
			<td>{{msg}}{{ form.title.errors }}</td>
		</tr>
		<tr>
			<td><label for="id_title">{% trans "Title" %}:</label></td>
			<td><input id="id_title" type="text" name="title" value="{{page.title}}" size="80"/></td>
		</tr>
		
		
		
		<tr>
			<td style="vertical-align:top"><label for="id_text">{% trans "Text" %}:</label></td>
			<td><textarea id="id_text" name="text" rows="20" cols="80">{{page.text}} {% if img %} <img src="{{ img }}" /> {% endif %}</textarea></td>
		</tr>
		
		<tr>
			<td colspan="2">
				<div class="button-left">
				{% with page.id|stringformat:"s" as p %}
					{% with "document.forms['edit'].action='"|add:p|add:"'"|add:"; document.forms['edit'].submit(); localStorage.clear();" as url %}
						{% button 'Send' url %}
					{% endwith %}
				{% endwith %}
					<input type="submit" value="{% trans "Send" %}" />
				</div>
				<div class="button-left">
					{% button 'Preview' 'document.forms["edit"].action="/doc/preview"; document.forms["edit"].submit(); setWikiPage()' %}
				</div>
				<div class="button-left">
					{% button 'Cancel' 'history.go(-1) ; localStorage.clear();' %}
				</div>
			</td>
		</tr>
		<tr>
			<td colspan="2">
				<a href="http://en.wikipedia.org/wiki/Markdown" target="_blank" class="normal">Markdown syntax</a>
			</td>
		</tr>
	</table>
</form>

<script>
$(document).ready(function() { getWikiPage(); });
</script>

{% endblock %}

src/lorepo/templates/wiki/edit_toc.html
{% extends "base.html" %}
{% load apptags %}
{% load wiki %}
{% load cache %}

{% block head %}
    <link href="/media/languages/languages.min.css" rel="stylesheet" type="text/css"/>
<script type="text/javascript" src="/media/js/jquery-ui-1.8.19.custom.js"></script>
<script type="text/javascript" src="/media/js/lib/jquery-ui-nestedSortable.js"></script>
<script type="text/javascript" src="/media/js/table-of-contents.js"></script>
<script type="text/javascript" src="/media/js/toc-disable-links.js"></script>
<script type="text/javascript" src="/media/js/equal-height.js"></script>
<script>
	$(document).ready(function() {
		equalHeight($(".sortable"));
	});
</script>
{% endblock %}

{% block content %}
<h1 class="page_header">Wiki pages - edit Table of contents</h1>
<div class="main clear" style="padding-top: 0"></div>

<div id="edit-toc-instructions">
	Contents from left column will be shown as Table of contents in the main Documentation page. 
	Contents which you don't want to be shown, insert on the right column.
	Simply grab content and drop it where you need it.
	You can also make a hierarchy in the Table of contents, 
	just drop selected content under ( and a little on the right ) content which you want to become a parent.
</div>

	<div id="wiki-two-box-wrapper">
		<div id="wiki-pages-list-wrapper-sortable" class="wiki-list-wrapper">
			<div id="table-of-contents-header-sortable">
				Table of contents
			</div>

			<div class="clear"></div>

			<ul id="wiki-pages-list-root-sortable" class="sortable">
				{% edit_toc wiki_pages %}
			</ul>
		</div>


		<div id="wiki-pages-list-wrapper-sortable" class="wiki-list-wrapper">
			<div id="table-of-contents-header-sortable">
				Other pages
			</div>

			<div class='clear'></div>

			<ul id="pages-list-root-sortable" class="sortable">
				{% edit_toc pages %}
			</ul>
		</div>
	<div class="clear"></div>
	<div class="button-left" id='serialize' style="margin-bottom:10px;">
		{% button 'Save' 'javascript:void(0)' %}
	</div>
	</div>

{% endblock %}

src/lorepo/templates/wiki/page.html
{% load apptags %}
{% load markdown_deux_tags %}
{% block content %}

<div class="wikiPage" id="{{page.id}}">

	<div class="wiki-page-preview-wrapper">
		<h4>{{ page.title }}</h4>
		{{page.text|markdown:"tables"}}
	</div>	

</div>

{% endblock %}

src/lorepo/templates/wiki/preview.html
{% extends "base.html" %}
{% load apptags %}
{% load markdown_deux_tags %}

{% block content %}

<div class="wikiPage">
	<h1 class="page_header">{{page.title}}</h1>
	<div class="main clear" style="padding-top: 0"></div>
	
	<div style="width:1,4em; float:left">{% button 'Go back' 'history.go(-1)' %}</div>
	<div class="clear"></div>
	
	<div>
	<h4>{{ page.title }}</h4>
	{{page.text|markdown:"tables"}}
	</div>	

</div>

{% endblock %}

src/lorepo/templates/wiki/table_of_contents.html
{% for wiki in wiki_pages %}
<li id="list_{{wiki.id}}">
	<div>
		<span class="wiki-page-more"></span>
        <a class="wiki-link {% if wiki.id == selected_page.id %}selected{% endif %}" href="/doc/{{ lang_code }}/page/{{wiki.url}}" id="{{wiki.id}}" ><div class="wiki-link-title">{{wiki.title}}</div></a>
        {% if translations_edit %} (
        {% for key, value in wiki.get_translations.items %}
            <a href="/doc/edit/{{ value.id }}" class="lang-xs" lang="{{ key }}">
                {% if value.needs_update %}<img src="/media/images/cross.png" />{% endif %}
            </a>
        {% endfor %})
        {% endif %}
	</div>
	{% if wiki.loaded_kids %}
        {% if translations_edit %}
            <ul>{% edit_toc wiki.loaded_kids%}</ul>
        {% else %}
		    <ul>{% toc wiki.loaded_kids selected_page lang_code%}</ul>
        {% endif %}
	{% endif %}
</li>
{% endfor %}

src/lorepo/templates/wiki/upload.html
{% extends "base.html" %}
{% load apptags %}
{% load markdown_deux_tags %}

{% block content %}

<h1 class="page_header">Wiki pages</h1>
<div class="main clear" style="padding-top: 0"></div>

<form method="post" action="{{ upload_url }}" name="upload" enctype="multipart/form-data">
	{% csrf_token %}
	<input type="hidden" name="next" value="{{next}}"/>
	<table class="upload-wiki">
  		{{ form }}
  	<tr>
		<th><div class="button-left">{% button 'Upload' 'document.forms["upload"].submit()' %}</div></th>
	  	<th><div class="button-left">{% button 'Cancel' 'history.go(-1)' %}</div></th>
	</tr>
  	</table>
  	<input type="submit" />
</form>
{% endblock %}